#!/usr/bin/env python3

import sys
import requests
import boto3
import time
import random
import subprocess 

#Creates bucket and grabs image URL , downloads and then uploads to my bucket
s3 = boto3.resource("s3")


randomNumber = str(random.randint(1000,9999)) #Generates random 4 digit number
bucket_name = 'YOUR-BUCKET-NAME-' + randomNumber
image_name = 'IMAGE_NAME_HERE'
image_url = 'https://' + bucket_name + '.s3.eu-west-1.amazonaws.com/' + image_name
			
try:
	response = s3.create_bucket(Bucket = bucket_name, CreateBucketConfiguration = {'LocationConstraint': 'eu-west-1'})
	print('Creating bucket...')
except Exception as error:
  print(error)
try:
	req_for_image = requests.get('URL-HERE-FOR-IMAGE-YOU-WANT-TO-DOWNLOAD', stream = True)
	file_object_from_req = req_for_image.raw
	req_data = file_object_from_req.read()
	s3.Bucket(bucket_name).put_object(Key = image_name , ContentType= '', Body = req_data, ACL = 'public-read')
except Exception as error:
 	print(error)


print("Creating instance in 5 seconds.")	
time.sleep(5)

#LAUNCH INSTANCE

ec2 = boto3.resource('ec2')
instances = ec2.create_instances(
  ImageId = 'IMAGE ID',
  MinCount = 1,
  MaxCount = 1,
  KeyName = 'YOURKEY',
 UserData="""#!/bin/bash
			 yum update -y
			 yum install httpd -y
			 systemctl enable httpd
			 systemctl start httpd
			 echo "<h2>Test page</h2>Instance ID: " > /var/www/html/index.html
			 curl --silent http://169.254.169.254/latest/meta-data/instance-id/ >> /var/www/html/index.html
			 echo "<br>Availability zone: " >> /var/www/html/index.html
			 curl --silent http://169.254.169.254/latest/meta-data/placement/availability-zone/ >> /var/www/html/index.html
			 echo "<br>IP address: " >> /var/www/html/index.html
			 curl --silent http://169.254.169.254/latest/meta-data/public-ipv4 >> /var/www/html/index.html
			 echo "<br> <img src=""" + image_url + """>" >> /var/www/html/index.html""",


  SecurityGroupIds = ['YOUR SECURITY GROUP HERE'],

  InstanceType = 't2.nano')
print(instances[0].id)

instance = instances[0]

# Wait for the instance to enter the running state
print("Waiting for instance to run...")
instance.wait_until_running()

# Reload the instance attributes
instance.load()
print("IP of Instance: " + instance.public_ip_address)



#Giving time for webpage to run
print("Loading..")
time.sleep(60)


print("Loading...")
time.sleep(60)


cmd1 = "ssh -o StrictHostKeyChecking=no -i 'YOURKEY.pem' ec2-user@" + instance.public_ip_address + ' sudo chmod 777 /var/www/html/index.html'
subprocess.run(cmd1, shell = True)

print("Waiting 30")
time.sleep(30)

#Prints availability zone to console.
cmd2 = "ssh -o StrictHostKeyChecking=no -i 'brett.pem' ec2-user@" + instance.public_ip_address + "" ' curl http://169.254.169.254/latest/meta-data/placement/availability-zone'
subprocess.run(cmd2, shell = True)
